"""The PowerShell InfraScope hands an endpoint to install RustDesk silently.

The script runs *on* the endpoint, as SYSTEM, and pulls everything it needs back
from InfraScope: its own config (id, password, options), the installer, and the
place to report the result. Nothing is pushed from the server - a Linux box
remote-executing on domain workstations is indistinguishable from lateral
movement and Kaspersky blocks it on this fleet. The trigger is whatever already
reaches the machine (a KSC "run script" task, a GPO startup script, a one-off
`schtasks /S <host> /RU SYSTEM`); InfraScope owns everything else.

Two things about the install are deliberate and easy to get wrong:

* **MSI, not `rustdesk.exe --silent-install`.** `--silent-install` never returns
  (the installer becomes the running app), so a script has to poll for the
  service and can never see a failure. `msiexec /qn` exits with a real code, and
  `CREATESTARTMENUSHORTCUTS=N CREATEDESKTOPSHORTCUTS=N INSTALLPRINTER=N` means no
  shortcuts and no phantom printer ever appear in front of the cashier.

* **Password before lockdown.** `disable-change-permanent-password=Y` makes
  `rustdesk.exe --password` a no-op, so the config is written in two passes: the
  working options first, the password, then the same file again with the locks.
"""

from __future__ import annotations

from app.core.config import settings

# `[options]` written on the first pass. `allow-logon-screen-password` is what
# lets an engineer in when the store PC sits at the lock screen - without it a
# locked machine refuses the permanent password. See docs/rustdesk-v2-plan.md.
BASE_OPTIONS: dict[str, str] = {
    "enable-check-update": "N",
    "enable-lan-discovery": "N",
    "direct-server": "N",
    "allow-logon-screen-password": "Y",
    "remove-preset-password-warning": "Y",
    "hide-help-cards": "Y",
}

# added when the device wants the client kept out of the user's way
HIDDEN_OPTIONS: dict[str, str] = {
    "hide-tray": "Y",
    "hide-stop-service": "Y",
    "allow-hide-cm": "Y",
    "hide-security-settings": "Y",
    "hide-network-settings": "Y",
    "hide-server-settings": "Y",
}

# added when the device is unattended (password, no on-screen "Accept")
UNATTENDED_OPTIONS: dict[str, str] = {
    "approve-mode": "password",
    "verification-method": "use-permanent-password",
}

# second pass only - these block `--password` and `--id`, so they go on last
LOCK_OPTIONS: dict[str, str] = {
    "disable-change-permanent-password": "Y",
    "disable-change-id": "Y",
}


def client_options(*, hidden: bool, unattended: bool) -> dict[str, str]:
    """The `[options]` block for a device, before the write-lock pass."""
    options = dict(BASE_OPTIONS)
    if hidden:
        options.update(HIDDEN_OPTIONS)
    if unattended:
        options.update(UNATTENDED_OPTIONS)
    return options


def public_url() -> str:
    """Base URL an endpoint uses to reach this API."""
    return settings.RUSTDESK_PUBLIC_URL.rstrip("/")


def deploy_command(api_prefix: str = "/api/v1") -> str:
    """The single line an operator pastes into KSC / GPO / schtasks."""
    url = f"{public_url()}{api_prefix}/remote-access/deploy/bootstrap.ps1"
    return (
        "powershell.exe -NoProfile -ExecutionPolicy Bypass -Command "
        f'"$c=New-Object Net.WebClient; '
        f"$c.Headers.Add('X-InfraScope-Deploy-Token','{settings.RUSTDESK_DEPLOY_TOKEN}'); "
        f"iex $c.DownloadString('{url}')\""
    )


def render_bootstrap(api_prefix: str = "/api/v1") -> str:
    """Render the endpoint script. Values are baked in; the per-machine config is
    fetched at run time so a password rotation needs no new script."""
    base = f"{public_url()}{api_prefix}/remote-access/deploy"
    return _TEMPLATE.replace("@@BASE@@", base).replace("@@TOKEN@@", settings.RUSTDESK_DEPLOY_TOKEN)


# `@@BASE@@` / `@@TOKEN@@` rather than str.format: the script is full of braces.
_TEMPLATE = r"""
# InfraScope - silent RustDesk rollout. Runs as SYSTEM on the endpoint.
# Generated by InfraScope; do not edit on the machine - edit the device row.
$ErrorActionPreference = 'Stop'
$ProgressPreference = 'SilentlyContinue'
[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12

$Base    = '@@BASE@@'
$Token   = '@@TOKEN@@'
$LogDir  = 'C:\ProgramData\InfraScope'
$Log     = Join-Path $LogDir 'rustdesk-configure.log'
$null    = New-Item -ItemType Directory -Force -Path $LogDir
function Log($m) { Add-Content $Log ("{0}  {1}" -f (Get-Date -Format 'yyyy-MM-ddTHH:mm:ss'), $m) }

$Headers = @{ 'X-InfraScope-Deploy-Token' = $Token }
$Host_   = $env:COMPUTERNAME
$Rid     = ''
$Version = ''

function Report($state, $detail) {
    try {
        $body = @{ hostname = $Host_; rustdesk_id = $Rid; version = $Version;
                   state = $state; detail = "$detail" } | ConvertTo-Json -Compress
        Invoke-RestMethod -Uri "$Base/report" -Method Post -Headers $Headers `
            -ContentType 'application/json' -Body $body -TimeoutSec 30 | Out-Null
    } catch { Log "report failed: $($_.Exception.Message)" }
}

try {
    Log "=== deploy start on $Host_ ==="

    # ---- 1. our own config -------------------------------------------------
    $cfgBody = @{ hostname = $Host_ } | ConvertTo-Json -Compress
    $cfg = Invoke-RestMethod -Uri "$Base/config" -Method Post -Headers $Headers `
        -ContentType 'application/json' -Body $cfgBody -TimeoutSec 30
    $Rid = $cfg.rustdesk_id
    Log "config: id=$Rid server=$($cfg.id_server) installer=$($cfg.installer_filename)"

    $exe = Join-Path $env:ProgramFiles 'RustDesk\rustdesk.exe'

    # ---- 2. install (skip when the wanted version is already there) --------
    $installed = $null
    try { $installed = (Get-ItemProperty 'HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\RustDesk\' -EA Stop).Version } catch { }
    if ($installed) { $Version = $installed }

    if (-not (Test-Path $exe) -or ($installed -ne $cfg.installer_version)) {
        $pkg = Join-Path $env:TEMP $cfg.installer_filename
        Log "downloading $($cfg.installer_filename) (have '$installed', want '$($cfg.installer_version)')"
        Invoke-WebRequest -Uri "$Base/installer" -Headers $Headers -OutFile $pkg -UseBasicParsing -TimeoutSec 900

        if ($cfg.installer_sha256) {
            $have = (Get-FileHash $pkg -Algorithm SHA256).Hash.ToLower()
            if ($have -ne $cfg.installer_sha256.ToLower()) {
                throw "installer checksum mismatch: got $have, expected $($cfg.installer_sha256)"
            }
        }

        if ($cfg.installer_filename -like '*.msi') {
            # /qn is genuinely silent and returns; the three properties keep the
            # Start Menu, the desktop and the printer list untouched.
            $msiLog = Join-Path $LogDir 'rustdesk-msi.log'
            $msiArgs = @('/i', "`"$pkg`"", '/qn', 'CREATESTARTMENUSHORTCUTS=N',
                      'CREATEDESKTOPSHORTCUTS=N', 'INSTALLPRINTER=N', '/l*v', "`"$msiLog`"")
            $p = Start-Process msiexec.exe -ArgumentList $msiArgs -Wait -PassThru
            if ($p.ExitCode -ne 0 -and $p.ExitCode -ne 3010) { throw "msiexec exit $($p.ExitCode), see $msiLog" }
        } else {
            # legacy .exe path: --silent-install never returns, so no -Wait
            Start-Process $pkg -ArgumentList '--silent-install' | Out-Null
            $deadline = (Get-Date).AddMinutes(5)
            while (-not (Test-Path $exe) -and (Get-Date) -lt $deadline) { Start-Sleep 5 }
            if (-not (Test-Path $exe)) { throw 'silent install did not produce rustdesk.exe' }
        }
        Remove-Item $pkg -Force -EA SilentlyContinue
        try { $Version = (Get-ItemProperty 'HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\RustDesk\' -EA Stop).Version } catch { }
        Log "installed version=$Version"
    } else {
        Log "already at $installed - skipping install"
    }
    if (-not (Test-Path $exe)) { throw "RustDesk not present at $exe after install" }
    Report 'installed' ''

    # ---- 3. service --------------------------------------------------------
    if (-not (Get-Service RustDesk -EA SilentlyContinue)) {
        Start-Process $exe -ArgumentList '--install-service' -Wait
        Start-Sleep 5
    }
    function Stop-RD {
        $s = Get-Service RustDesk -EA SilentlyContinue
        if ($s -and $s.Status -ne 'Stopped') {
            try { Stop-Service RustDesk -Force -EA Stop } catch { & sc.exe stop RustDesk | Out-Null }
        }
        Start-Sleep 2
        Get-Process rustdesk -EA SilentlyContinue | Stop-Process -Force -EA SilentlyContinue
        Start-Sleep 2
    }

    # The SYSTEM service reads its config from the systemprofile directory; the
    # LocalService one can hold stale rs-ny.rustdesk.com defaults. Write both.
    $cfgDirs = @(
        (Join-Path $env:WINDIR 'ServiceProfiles\LocalService\AppData\Roaming\RustDesk\config'),
        (Join-Path $env:WINDIR 'System32\config\systemprofile\AppData\Roaming\RustDesk\config')
    )

    function Write-Config([hashtable]$opts) {
        $lines = @("rendezvous_server = '$($cfg.id_server)'", 'nat_type = 1', 'serial = 0', '', '[options]')
        $lines += "custom-rendezvous-server = '$($cfg.id_server)'"
        $lines += "relay-server = '$($cfg.relay_server)'"
        $lines += "api-server = '$($cfg.api_server)'"
        $lines += "key = '$($cfg.key)'"
        foreach ($k in ($opts.Keys | Sort-Object)) { $lines += "$k = '$($opts[$k])'" }
        $toml = ($lines -join "`r`n") + "`r`n"
        foreach ($d in $cfgDirs) {
            $null = New-Item -ItemType Directory -Force -Path $d
            Set-Content (Join-Path $d 'RustDesk2.toml') $toml -Encoding UTF8
            # keep everything except the id line, then put our id back on top
            $idf = Join-Path $d 'RustDesk.toml'
            $keep = @()
            if (Test-Path $idf) { $keep = Get-Content $idf | Where-Object { $_ -notmatch '^\s*(enc_id|id)\s*=' } }
            Set-Content $idf (@("id = '$Rid'") + $keep) -Encoding UTF8
        }
    }

    # ---- 4. first pass: working config, no write locks ---------------------
    $opts = @{}
    foreach ($p in $cfg.options.PSObject.Properties) { $opts[$p.Name] = $p.Value }
    Stop-RD
    Write-Config $opts
    try { Start-Service RustDesk } catch { & sc.exe start RustDesk | Out-Null }
    Start-Sleep 6
    Log 'server + id written'

    # ---- 5. permanent password (must precede the locks) --------------------
    if ($cfg.permanent_password) {
        & $exe --password $cfg.permanent_password
        Start-Sleep 5
        $ok = $false
        foreach ($d in $cfgDirs) {
            $rd = Join-Path $d 'RustDesk.toml'
            if ((Get-Content $rd -EA SilentlyContinue) -match "^\s*password\s*=\s*'.+'") { $ok = $true }
        }
        if ($ok) { Log 'password set + verified' }
        else { throw 'password did not persist to RustDesk.toml' }
    }

    # ---- 6. second pass: same config plus the write locks ------------------
    if ($cfg.lock_options) {
        foreach ($p in $cfg.lock_options.PSObject.Properties) { $opts[$p.Name] = $p.Value }
        Write-Config $opts
        try { Restart-Service RustDesk -EA Stop } catch { }
        Log 'config locked'
    }

    # ---- 7. keep it out of the user's way ----------------------------------
    if ($cfg.hidden) {
        $links = @("$env:ProgramData\Microsoft\Windows\Start Menu\Programs\RustDesk.lnk",
                   "$env:PUBLIC\Desktop\RustDesk.lnk")
        Get-ChildItem 'C:\Users' -Directory -EA SilentlyContinue | ForEach-Object {
            $links += "$($_.FullName)\Desktop\RustDesk.lnk"
            $links += "$($_.FullName)\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\RustDesk.lnk"
        }
        foreach ($l in $links) { if (Test-Path $l) { Remove-Item $l -Force -EA SilentlyContinue } }
        Log 'shortcuts removed'
    }

    if ($cfg.block_outgoing) {
        # AppLocker: non-admins cannot start rustdesk.exe interactively. The
        # SYSTEM service instance is unaffected, so incoming sessions still work.
        try {
            Set-Service AppIDSvc -StartupType Automatic -EA SilentlyContinue
            Start-Service AppIDSvc -EA SilentlyContinue
            $xml = @"
<AppLockerPolicy Version="1">
  <RuleCollection Type="Exe" EnforcementMode="Enabled">
    <FilePathRule Id="e1f7a1a0-0000-0000-0000-infrascope01" Name="InfraScope: allow RustDesk for admins" Description="" UserOrGroupSid="S-1-5-32-544" Action="Allow">
      <Conditions><FilePathCondition Path="%PROGRAMFILES%\RustDesk\*"/></Conditions>
    </FilePathRule>
    <FilePathRule Id="e1f7a1a0-0000-0000-0000-infrascope02" Name="InfraScope: deny RustDesk for users" Description="" UserOrGroupSid="S-1-1-0" Action="Deny">
      <Conditions><FilePathCondition Path="%PROGRAMFILES%\RustDesk\*"/></Conditions>
    </FilePathRule>
    <FilePathRule Id="e1f7a1a0-0000-0000-0000-infrascope03" Name="(default) allow everything else" Description="" UserOrGroupSid="S-1-1-0" Action="Allow">
      <Conditions><FilePathCondition Path="*"/></Conditions>
    </FilePathRule>
  </RuleCollection>
</AppLockerPolicy>
"@
            $tmp = Join-Path $LogDir 'rustdesk-applocker.xml'
            Set-Content $tmp $xml -Encoding UTF8
            Set-AppLockerPolicy -XmlPolicy $tmp -Merge -EA Stop
            Log 'AppLocker deny rule applied'
        } catch { Log "AppLocker step skipped: $($_.Exception.Message)" }
    }

    Report 'configured' ''
    Log '=== deploy done ==='
} catch {
    $msg = $_.Exception.Message
    Log "FAILED: $msg"
    Report 'failed' $msg
    exit 1
}
"""
